// Compiles data/questions.json (readable, editable, the authoring source)
// into src/data/keys.generated.js (what actually ships).
//
// Two things change in the crossing. Answers become salted hashes, so the
// shipped bundle can score a guess without ever containing the answer list.
// And quips move into a shared pool addressed by index, so the strings that
// survive in the bundle can't be traced back to the answers they belong to.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { normalize } from '../src/normalize.js'
import { keyHash } from '../src/hash.js'

const here = dirname(fileURLToPath(import.meta.url))
const TIER_ORDER = ['dust', 'tooclever', 'flocker', 'rare', 'farout', 'astronomical']

const doc = JSON.parse(readFileSync(join(here, '..', 'data', 'questions.json')))

const quipPool = []
const quipIndex = new Map()
const quipRef = (text) => {
  if (!text) return -1
  if (!quipIndex.has(text)) {
    quipIndex.set(text, quipPool.length)
    quipPool.push(text)
  }
  return quipIndex.get(text)
}

let collisions = 0
let keyCount = 0
const questions = doc.questions.map((q) => {
  const keys = {}
  const origin = new Map() // hash -> the answer that claimed it, for the error
  for (const [name, tier, quip, aliases = []] of q.answers) {
    const tierIdx = TIER_ORDER.indexOf(tier)
    for (const form of [name, ...aliases]) {
      const norm = normalize(form)
      if (!norm) continue
      const h = keyHash(q.id, norm)
      if (h in keys && origin.get(h) !== name) {
        console.error(`  hash collision in [${q.id}]: "${form}" vs "${origin.get(h)}"`)
        collisions++
      }
      keys[h] = [tierIdx, quipRef(quip)]
      origin.set(h, name)
      keyCount++
    }
  }
  return { id: q.id, prompt: q.prompt, note: q.note ?? '', keys }
})

if (collisions) {
  console.error(`\n${collisions} hash collision(s) — change the salt in src/hash.js.`)
  process.exit(1)
}

mkdirSync(join(here, '..', 'src', 'data'), { recursive: true })
const out =
  '// GENERATED by scripts/build-answers.mjs — do not edit.\n' +
  '// Edit data/questions.json and run `npm run keys`.\n' +
  'export const QUIPS = ' +
  JSON.stringify(quipPool) +
  '\nexport const QUESTIONS = ' +
  JSON.stringify(questions) +
  '\n'
writeFileSync(join(here, '..', 'src', 'data', 'keys.generated.js'), out)

console.log(
  `built ${questions.length} questions · ${keyCount} keys · ${quipPool.length} quips ` +
    `· ${(out.length / 1024).toFixed(0)} KB`
)
